aesByteEncryptor:
  secret: "JKBoardPassword"
  salt: "123F123F123A"

# HS512 알고리즘을 사용하기 떄문에 512bit (64byte 이상의 secret key를 사용해야 한다.)
# Secret 값은 특정 문자열을 Base64로 인코딩한 값 사용
jwt:
  secret: "amtib2FyZF8yMDE1MDUzMTIwMjMwNTA2MTk5MzA5MjQxOTkzMTAyOV9qa2JvYXJk"
